In [3]:
import pandas as pd 
df=pd.read_csv('Pokemon.csv')
df.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

In [25]:
df.iloc[2,1]

'Venusaur'

In [29]:
df.loc[df['Type 1']=='Fire']

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
42,37,Vulpix,Fire,NaN,299,38,41,40,50,65,65,1,False
43,38,Ninetales,Fire,NaN,505,73,76,75,81,100,100,1,False
63,58,Growlithe,Fire,NaN,350,55,70,45,70,50,60,1,False
64,59,Arcanine,Fire,NaN,555,90,110,80,100,80,95,1,False
83,77,Ponyta,Fire,NaN,410,50,85,55,65,65,90,1,False
84,78,Rapidash,Fire,NaN,500,65,100,70,80,80,105,1,False
135,126,Magmar,Fire,NaN,495,65,95,57,100,85,93,1,False
147,136,Flareon,Fire,NaN,525,65,130,60,95,110,65,1,False
158,146,Moltres,Fire,Flying,580,90,100,90,125,85,90,1,True
169,155,Cyndaquil,Fire,NaN,309,39,52,43,60,50,65,2,False
170,156,Quilava,Fire,NaN,405,58,64,58,80,65,80,2,False
171,157,Typhlosion,Fire,NaN,534,78,84,78,109,85,100,2,False
236,218,Slugma,Fire,NaN,250,40,40,40,70,40,20,2,False
237,219,Magcargo,Fire,Rock,410,50,50,120,80,80,30,2,False
259,240,Magby,Fire,NaN,365,45,75,37,70,55,83,2,False
263,244,Entei,Fire,NaN,580,115,115,85,90,75,100,2,True
270,250,Ho-oh,Fire,Flying,680,106,130,90,110,154,90,2,True
276,255,Torchic,Fire,NaN,310,45,60,40,70,50,45,3,False
277,256,Combusken,Fire,Fighting,405,60,85,60,85,60,55,3,False
278,257,Blaziken,Fire,Fighting,530,80,120,70,110,70,80,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,630,80,160,80,130,80,100,3,False
352,322,Numel,Fire,Ground,305,60,60,40,65,45,35,3,False
353,323,Camerupt,Fire,Ground,460,70,100,70,105,75,40,3,False
354,323,CameruptMega Camerupt,Fire,Ground,560,70,120,100,145,105,20,3,False
355,324,Torkoal,Fire,NaN,470,70,85,140,85,70,20,3,False
435,390,Chimchar,Fire,NaN,309,44,58,44,58,44,61,4,False
436,391,Monferno,Fire,Fighting,405,64,78,52,78,52,81,4,False
437,392,Infernape,Fire,Fighting,534,76,104,71,104,71,108,4,False
518,467,Magmortar,Fire,NaN,540,75,95,67,125,95,83,4,False
542,485,Heatran,Fire,Steel,600,91,90,106,130,106,77,4,True
557,498,Tepig,Fire,NaN,308,65,63,45,45,45,45,5,False
558,499,Pignite,Fire,Fighting,418,90,93,55,70,55,55,5,False
559,500,Emboar,Fire,Fighting,528,110,123,65,100,65,65,5,False
572,513,Pansear,Fire,NaN,316,50,53,48,53,48,64,5,False
573,514,Simisear,Fire,NaN,498,75,98,63,98,63,101,5,False
614,554,Darumaka,Fire,NaN,315,70,90,45,15,45,50,5,False
615,555,DarmanitanStandard Mode,Fire,NaN,480,105,140,55,30,55,95,5,False
616,555,DarmanitanZen Mode,Fire,Psychic,540,105,30,105,140,105,55,5,False
692,631,Heatmor,Fire,NaN,484,85,97,66,105,66,65,5,False
721,653,Fennekin,Fire,NaN,307,40,45,40,62,60,60,6,False
722,654,Braixen,Fire,NaN,409,59,59,58,90,70,73,6,False
723,655,Delphox,Fire,Psychic,534,75,69,72,114,100,104,6,False
730,662,Fletchinder,Fire,Flying,382,62,73,55,56,52,84,6,False
731,663,Talonflame,Fire,Flying,499,78,81,71,74,69,126,6,False
735,667,Litleo,Fire,Normal,369,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,507,86,68,72,109,66,106,6,False
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

Iteration in a dataFrame

In [28]:
for index,row in df.iterrows():
    print(index+1,row['Name'])

1 Bulbasaur
2 Ivysaur
3 Venusaur
4 VenusaurMega Venusaur
5 Charmander
6 Charmeleon
7 Charizard
8 CharizardMega Charizard X
9 CharizardMega Charizard Y
10 Squirtle
11 Wartortle
12 Blastoise
13 BlastoiseMega Blastoise
14 Caterpie
15 Metapod
16 Butterfree
17 Weedle
18 Kakuna
19 Beedrill
20 BeedrillMega Beedrill
21 Pidgey
22 Pidgeotto
23 Pidgeot
24 PidgeotMega Pidgeot
25 Rattata
26 Raticate
27 Spearow
28 Fearow
29 Ekans
30 Arbok
31 Pikachu
32 Raichu
33 Sandshrew
34 Sandslash
35 Nidoran♀
36 Nidorina
37 Nidoqueen
38 Nidoran♂
39 Nidorino
40 Nidoking
41 Clefairy
42 Clefable
43 Vulpix
44 Ninetales
45 Jigglypuff
46 Wigglytuff
47 Zubat
48 Golbat
49 Oddish
50 Gloom
51 Vileplume
52 Paras
53 Parasect
54 Venonat
55 Venomoth
56 Diglett
57 Dugtrio
58 Meowth
59 Persian
60 Psyduck
61 Golduck
62 Mankey
63 Primeape
64 Growlithe
65 Arcanine
66 Poliwag
67 Poliwhirl
68 Poliwrath
69 Abra
70 Kadabra
71 Alakazam
72 AlakazamMega Alakazam
73 Machop
74 Machoke
75 Machamp
76 Bellsprout
77 Weepinbell
78 Victreebel
79 Tentacool
80 Tentacruel
81 Geodude
82 Graveler
83 Golem
84 Ponyta
85 Rapidash
86 Slowpoke
87 Slowbro
88 SlowbroMega Slowbro
89 Magnemite
90 Magneton
91 Farfetch'd
92 Doduo
93 Dodrio
94 Seel
95 Dewgong
96 Grimer
97 Muk
98 Shellder
99 Cloyster
100 Gastly
101 Haunter
102 Gengar
103 GengarMega Gengar
104 Onix
105 Drowzee
106 Hypno
107 Krabby
108 Kingler
109 Voltorb
110 Electrode
111 Exeggcute
112 Exeggutor
113 Cubone
114 Marowak
115 Hitmonlee
116 Hitmonchan
117 Lickitung
118 Koffing
119 Weezing
120 Rhyhorn
121 Rhydon
122 Chansey
123 Tangela
124 Kangaskhan
125 KangaskhanMega Kangaskhan
126 Horsea
127 Seadra
128 Goldeen
129 Seaking
130 Staryu
131 Starmie
132 Mr. Mime
133 Scyther
134 Jynx
135 Electabuzz
136 Magmar
137 Pinsir
138 PinsirMega Pinsir
139 Tauros
140 Magikarp
141 Gyarados
142 GyaradosMega Gyarados
143 Lapras
144 Ditto
145 Eevee
146 Vaporeon
147 Jolteon
148 Flareon
149 Porygon
150 Omanyte
151 Omastar
152 Kabuto
153 Kabutops
154 Aerodactyl
155 AerodactylMega Aerodactyl
156 Snorlax
157 Articuno
158 Zapdos
159 Moltres
160 Dratini
161 Dragonair
162 Dragonite
163 Mewtwo
164 MewtwoMega Mewtwo X
165 MewtwoMega Mewtwo Y
166 Mew
167 Chikorita
168 Bayleef
169 Meganium
170 Cyndaquil
171 Quilava
172 Typhlosion
173 Totodile
174 Croconaw
175 Feraligatr
176 Sentret
177 Furret
178 Hoothoot
179 Noctowl
180 Ledyba
181 Ledian
182 Spinarak
183 Ariados
184 Crobat
185 Chinchou
186 Lanturn
187 Pichu
188 Cleffa
189 Igglybuff
190 Togepi
191 Togetic
192 Natu
193 Xatu
194 Mareep
195 Flaaffy
196 Ampharos
197 AmpharosMega Ampharos
198 Bellossom
199 Marill
200 Azumarill
201 Sudowoodo
202 Politoed
203 Hoppip
204 Skiploom
205 Jumpluff
206 Aipom
207 Sunkern
208 Sunflora
209 Yanma
210 Wooper
211 Quagsire
212 Espeon
213 Umbreon
214 Murkrow
215 Slowking
216 Misdreavus
217 Unown
218 Wobbuffet
219 Girafarig
220 Pineco
221 Forretress
222 Dunsparce
223 Gligar
224 Steelix
225 SteelixMega Steelix
226 Snubbull
227 Granbull
228 Qwilfish
229 Scizor
230 ScizorMega Scizor
231 Shuckle
232 Heracross
233 HeracrossMega Heracross
234 Sneasel
235 Teddiursa
236 Ursaring
237 Slugma
238 Magcargo
239 Swinub
240 Piloswine
241 Corsola
242 Remoraid
243 Octillery
244 Delibird
245 Mantine
246 Skarmory
247 Houndour
248 Houndoom
249 HoundoomMega Houndoom
250 Kingdra
251 Phanpy
252 Donphan
253 Porygon2
254 Stantler
255 Smeargle
256 Tyrogue
257 Hitmontop
258 Smoochum
259 Elekid
260 Magby
261 Miltank
262 Blissey
263 Raikou
264 Entei
265 Suicune
266 Larvitar
267 Pupitar
268 Tyranitar
269 TyranitarMega Tyranitar
270 Lugia
271 Ho-oh
272 Celebi
273 Treecko
274 Grovyle
275 Sceptile
276 SceptileMega Sceptile
277 Torchic
278 Combusken
279 Blaziken
280 BlazikenMega Blaziken
281 Mudkip
282 Marshtomp
283 Swampert
284 SwampertMega Swampert
285 Poochyena
286 Mightyena
287 Zigzagoon
288 Linoone
289 Wurmple
290 Silcoon
291 Beautifly
292 Cascoon
293 Dustox
294 Lotad
295 Lombre
296 Ludicolo
297 Seedot
298 Nuzleaf
299 Shiftry
300 Taillow
301 Swellow
302 Wingull
303 Pelipper
304 Ralts
305 Kirlia
306 Gardevoir
307 GardevoirMega Gardevoir
308 Surskit
309 Masquerain
310 Shroomish
311 Breloom
312 Slakoth
313 Vigoroth
314 Slaking
315 Nincada
316 Ninjask
317 Shedinja
318 Whismur
319 Loudred
320 Exploud
321 Makuhita
322 Hariyama
323 Azurill
324 Nosepass
325 Skitty
326 Delcatty
327 Sableye
328 SableyeMega Sableye
329 Mawile
330 MawileMega Mawile
331 Aron
332 Lairon
333 Aggron
334 AggronMega Aggron
335 Meditite
336 Medicham
337 MedichamMega Medicham
338 Electrike
339 Manectric
340 ManectricMega Manectric
341 Plusle
342 Minun
343 Volbeat
344 Illumise
345 Roselia
346 Gulpin
347 Swalot
348 Carvanha
349 Sharpedo
350 SharpedoMega Sharpedo
351 Wailmer
352 Wailord
353 Numel
354 Camerupt
355 CameruptMega Camerupt
356 Torkoal
357 Spoink
358 Grumpig
359 Spinda
360 Trapinch
361 Vibrava
362 Flygon
363 Cacnea
364 Cacturne
365 Swablu
366 Altaria
367 AltariaMega Altaria
368 Zangoose
369 Seviper
370 Lunatone
371 Solrock
372 Barboach
373 Whiscash
374 Corphish
375 Crawdaunt
376 Baltoy
377 Claydol
378 Lileep
379 Cradily
380 Anorith
381 Armaldo
382 Feebas
383 Milotic
384 Castform
385 Kecleon
386 Shuppet
387 Banette
388 BanetteMega Banette
389 Duskull
390 Dusclops
391 Tropius
392 Chimecho
393 Absol
394 AbsolMega Absol
395 Wynaut
396 Snorunt
397 Glalie
398 GlalieMega Glalie
399 Spheal
400 Sealeo
401 Walrein
402 Clamperl
403 Huntail
404 Gorebyss
405 Relicanth
406 Luvdisc
407 Bagon
408 Shelgon
409 Salamence
410 SalamenceMega Salamence
411 Beldum
412 Metang
413 Metagross
414 MetagrossMega Metagross
415 Regirock
416 Regice
417 Registeel
418 Latias
419 LatiasMega Latias
420 Latios
421 LatiosMega Latios
422 Kyogre
423 KyogrePrimal Kyogre
424 Groudon
425 GroudonPrimal Groudon
426 Rayquaza
427 RayquazaMega Rayquaza
428 Jirachi
429 DeoxysNormal Forme
430 DeoxysAttack Forme
431 DeoxysDefense Forme
432 DeoxysSpeed Forme
433 Turtwig
434 Grotle
435 Torterra
436 Chimchar
437 Monferno
438 Infernape
439 Piplup
440 Prinplup
441 Empoleon
442 Starly
443 Staravia
444 Staraptor
445 Bidoof
446 Bibarel
447 Kricketot
448 Kricketune
449 Shinx
450 Luxio
451 Luxray
452 Budew
453 Roserade
454 Cranidos
455 Rampardos
456 Shieldon
457 Bastiodon
458 Burmy
459 WormadamPlant Cloak
460 WormadamSandy Cloak
461 WormadamTrash Cloak
462 Mothim
463 Combee
464 Vespiquen
465 Pachirisu
466 Buizel
467 Floatzel
468 Cherubi
469 Cherrim
470 Shellos
471 Gastrodon
472 Ambipom
473 Drifloon
474 Drifblim
475 Buneary
476 Lopunny
477 LopunnyMega Lopunny
478 Mismagius
479 Honchkrow
480 Glameow
481 Purugly
482 Chingling
483 Stunky
484 Skuntank
485 Bronzor
486 Bronzong
487 Bonsly
488 Mime Jr.
489 Happiny
490 Chatot
491 Spiritomb
492 Gible
493 Gabite
494 Garchomp
495 GarchompMega Garchomp
496 Munchlax
497 Riolu
498 Lucario
499 LucarioMega Lucario
500 Hippopotas
501 Hippowdon
502 Skorupi
503 Drapion
504 Croagunk
505 Toxicroak
506 Carnivine
507 Finneon
508 Lumineon
509 Mantyke
510 Snover
511 Abomasnow
512 AbomasnowMega Abomasnow
513 Weavile
514 Magnezone
515 Lickilicky
516 Rhyperior
517 Tangrowth
518 Electivire
519 Magmortar
520 Togekiss
521 Yanmega
522 Leafeon
523 Glaceon
524 Gliscor
525 Mamoswine
526 Porygon-Z
527 Gallade
528 GalladeMega Gallade
529 Probopass
530 Dusknoir
531 Froslass
532 Rotom
533 RotomHeat Rotom
534 RotomWash Rotom
535 RotomFrost Rotom
536 RotomFan Rotom
537 RotomMow Rotom
538 Uxie
539 Mesprit
540 Azelf
541 Dialga
542 Palkia
543 Heatran
544 Regigigas
545 GiratinaAltered Forme
546 GiratinaOrigin Forme
547 Cresselia
548 Phione
549 Manaphy
550 Darkrai
551 ShayminLand Forme
552 ShayminSky Forme
553 Arceus
554 Victini
555 Snivy
556 Servine
557 Serperior
558 Tepig
559 Pignite
560 Emboar
561 Oshawott
562 Dewott
563 Samurott
564 Patrat
565 Watchog
566 Lillipup
567 Herdier
568 Stoutland
569 Purrloin
570 Liepard
571 Pansage
572 Simisage
573 Pansear
574 Simisear
575 Panpour
576 Simipour
577 Munna
578 Musharna
579 Pidove
580 Tranquill
581 Unfezant
582 Blitzle
583 Zebstrika
584 Roggenrola
585 Boldore
586 Gigalith
587 Woobat
588 Swoobat
589 Drilbur
590 Excadrill
591 Audino
592 AudinoMega Audino
593 Timburr
594 Gurdurr
595 Conkeldurr
596 Tympole
597 Palpitoad
598 Seismitoad
599 Throh
600 Sawk
601 Sewaddle
602 Swadloon
603 Leavanny
604 Venipede
605 Whirlipede
606 Scolipede
607 Cottonee
608 Whimsicott
609 Petilil
610 Lilligant
611 Basculin
612 Sandile
613 Krokorok
614 Krookodile
615 Darumaka
616 DarmanitanStandard Mode
617 DarmanitanZen Mode
618 Maractus
619 Dwebble
620 Crustle
621 Scraggy
622 Scrafty
623 Sigilyph
624 Yamask
625 Cofagrigus
626 Tirtouga
627 Carracosta
628 Archen
629 Archeops
630 Trubbish
631 Garbodor
632 Zorua
633 Zoroark
634 Minccino
635 Cinccino
636 Gothita
637 Gothorita
638 Gothitelle
639 Solosis
640 Duosion
641 Reuniclus
642 Ducklett
643 Swanna
644 Vanillite
645 Vanillish
646 Vanilluxe
647 Deerling
648 Sawsbuck
649 Emolga
650 Karrablast
651 Escavalier
652 Foongus
653 Amoonguss
654 Frillish
655 Jellicent
656 Alomomola
657 Joltik
658 Galvantula
659 Ferroseed
660 Ferrothorn
661 Klink
662 Klang
663 Klinklang
664 Tynamo
665 Eelektrik
666 Eelektross
667 Elgyem
668 Beheeyem
669 Litwick
670 Lampent
671 Chandelure
672 Axew
673 Fraxure
674 Haxorus
675 Cubchoo
676 Beartic
677 Cryogonal
678 Shelmet
679 Accelgor
680 Stunfisk
681 Mienfoo
682 Mienshao
683 Druddigon
684 Golett
685 Golurk
686 Pawniard
687 Bisharp
688 Bouffalant
689 Rufflet
690 Braviary
691 Vullaby
692 Mandibuzz
693 Heatmor
694 Durant
695 Deino
696 Zweilous
697 Hydreigon
698 Larvesta
699 Volcarona
700 Cobalion
701 Terrakion
702 Virizion
703 TornadusIncarnate Forme
704 TornadusTherian Forme
705 ThundurusIncarnate Forme
706 ThundurusTherian Forme
707 Reshiram
708 Zekrom
709 LandorusIncarnate Forme
710 LandorusTherian Forme
711 Kyurem
712 KyuremBlack Kyurem
713 KyuremWhite Kyurem
714 KeldeoOrdinary Forme
715 KeldeoResolute Forme
716 MeloettaAria Forme
717 MeloettaPirouette Forme
718 Genesect
719 Chespin
720 Quilladin
721 Chesnaught
722 Fennekin
723 Braixen
724 Delphox
725 Froakie
726 Frogadier
727 Greninja
728 Bunnelby
729 Diggersby
730 Fletchling
731 Fletchinder
732 Talonflame
733 Scatterbug
734 Spewpa
735 Vivillon
736 Litleo
737 Pyroar
738 Flabébé
739 Floette
740 Florges
741 Skiddo
742 Gogoat
743 Pancham
744 Pangoro
745 Furfrou
746 Espurr
747 MeowsticMale
748 MeowsticFemale
749 Honedge
750 Doublade
751 AegislashBlade Forme
752 AegislashShield Forme
753 Spritzee
754 Aromatisse
755 Swirlix
756 Slurpuff
757 Inkay
758 Malamar
759 Binacle
760 Barbaracle
761 Skrelp
762 Dragalge
763 Clauncher
764 Clawitzer
765 Helioptile
766 Heliolisk
767 Tyrunt
768 Tyrantrum
769 Amaura
770 Aurorus
771 Sylveon
772 Hawlucha
773 Dedenne
774 Carbink
775 Goomy
776 Sliggoo
777 Goodra
778 Klefki
779 Phantump
780 Trevenant
781 PumpkabooAverage Size
782 PumpkabooSmall Size
783 PumpkabooLarge Size
784 PumpkabooSuper Size
785 GourgeistAverage Size
786 GourgeistSmall Size
787 GourgeistLarge Size
788 GourgeistSuper Size
789 Bergmite
790 Avalugg
791 Noibat
792 Noivern
793 Xerneas
794 Yveltal
795 Zygarde50% Forme
796 Diancie
797 DiancieMega Diancie
798 HoopaHoopa Confined
799 HoopaHoopa Unbound
800 Volcanion

In [30]:
df.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [37]:
df.sort_values(['Attack','Defense'],ascending=[1,0])

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
121,113,Chansey,Normal,NaN,450,250,5,5,35,105,50,1,False
488,440,Happiny,Normal,NaN,220,100,5,5,15,65,30,4,False
230,213,Shuckle,Bug,Rock,505,20,10,230,10,230,5,2,False
139,129,Magikarp,Water,NaN,200,20,10,55,15,20,80,1,False
261,242,Blissey,Normal,NaN,540,255,10,10,75,135,55,2,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
424,383,GroudonPrimal Groudon,Ground,Fire,770,100,180,160,150,90,90,3,True
426,384,RayquazaMega Rayquaza,Dragon,Flying,780,105,180,100,180,100,115,3,True
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True
232,214,HeracrossMega Heracross,Bug,Fighting,600,80,185,115,40,105,75,2,False
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True

Making Changes to Data

In [38]:
df.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [44]:
#df['Total']=df['HP']+df['Attack']+df['Defense']+df['Sp. Atk']+df['Sp. Def']+df['Speed']

# df=df.drop(columns=['Total'])
df.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [47]:
df['Total']=df.iloc[:,4:10].sum(axis=1)
df.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309

In [51]:
cols=list(df.columns.values)
df=df[cols[0:4]+[cols[-1]]+cols[4:12]]
df.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

Saving the Updated File

In [53]:
df.to_csv('modified_pokemon.csv',index=False)

Filtering

In [75]:
new_df=df.loc[(df['Type 1']=='Grass') & (df['Type 2']=='Poison')& (df['HP']>50)]
#df.loc[(df['Type 1']=='Grass') | (df['Type 2']=='Poison')& (df['HP']>80)]
new_df.to_csv('filtered.csv')

#new_df=new_df.reset_index() will not delete the col
new_df=new_df.reset_index(drop=True)#will delete the col
new_df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
1,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
2,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
3,44,Gloom,Grass,Poison,395,60,65,70,85,75,40,1,False
4,45,Vileplume,Grass,Poison,490,75,80,85,110,90,50,1,False
5,70,Weepinbell,Grass,Poison,390,65,90,50,85,45,55,1,False
6,71,Victreebel,Grass,Poison,490,80,105,65,100,70,70,1,False
7,407,Roserade,Grass,Poison,515,60,70,65,125,105,90,4,False
8,590,Foongus,Grass,Poison,294,69,55,45,55,55,15,5,False
9,591,Amoonguss,Grass,Poison,464,114,85,70,85,80,30,5,False

Filtering names containing mega

In [ ]:
df.loc[df['Name'].str.contains('Mega')]
#not containing mega ~df.loc[df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False
71,65,AlakazamMega Alakazam,Psychic,NaN,590,55,50,65,175,95,150,1,False
87,80,SlowbroMega Slowbro,Water,Psychic,590,95,75,180,130,80,30,1,False
102,94,GengarMega Gengar,Ghost,Poison,600,60,65,80,170,95,130,1,False
124,115,KangaskhanMega Kangaskhan,Normal,NaN,590,105,125,100,60,100,100,1,False
137,127,PinsirMega Pinsir,Bug,Flying,600,65,155,120,65,90,105,1,False
141,130,GyaradosMega Gyarados,Water,Dark,640,95,155,109,70,130,81,1,False
154,142,AerodactylMega Aerodactyl,Rock,Flying,615,80,135,85,70,95,150,1,False
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,780,106,150,70,194,120,140,1,True
168,154,Meganium,Grass,NaN,525,80,82,100,83,100,80,2,False
196,181,AmpharosMega Ampharos,Electric,Dragon,610,90,95,105,165,110,45,2,False
224,208,SteelixMega Steelix,Steel,Ground,610,75,125,230,55,95,30,2,False
229,212,ScizorMega Scizor,Bug,Steel,600,70,150,140,65,100,75,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,600,80,185,115,40,105,75,2,False
248,229,HoundoomMega Houndoom,Dark,Fire,600,75,90,90,140,90,115,2,False
268,248,TyranitarMega Tyranitar,Rock,Dark,700,100,164,150,95,120,71,2,False
275,254,SceptileMega Sceptile,Grass,Dragon,630,70,110,75,145,85,145,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,630,80,160,80,130,80,100,3,False
283,260,SwampertMega Swampert,Water,Ground,635,100,150,110,95,110,70,3,False
306,282,GardevoirMega Gardevoir,Psychic,Fairy,618,68,85,65,165,135,100,3,False
327,302,SableyeMega Sableye,Dark,Ghost,480,50,85,125,85,115,20,3,False
329,303,MawileMega Mawile,Steel,Fairy,480,50,105,125,55,95,50,3,False
333,306,AggronMega Aggron,Steel,NaN,630,70,140,230,60,80,50,3,False
336,308,MedichamMega Medicham,Fighting,Psychic,510,60,100,85,80,85,100,3,False
339,310,ManectricMega Manectric,Electric,NaN,575,70,75,80,135,80,135,3,False
349,319,SharpedoMega Sharpedo,Water,Dark,560,70,140,70,110,65,105,3,False
354,323,CameruptMega Camerupt,Fire,Ground,560,70,120,100,145,105,20,3,False
366,334,AltariaMega Altaria,Dragon,Fairy,590,75,110,110,110,105,80,3,False
387,354,BanetteMega Banette,Ghost,NaN,555,64,165,75,93,83,75,3,False
393,359,AbsolMega Absol,Dark,NaN,565,65,150,60,115,60,115,3,False
397,362,GlalieMega Glalie,Ice,NaN,580,80,120,80,120,80,100,3,False
409,373,SalamenceMega Salamence,Dragon,Flying,700,95,145,130,120,90,120,3,False
413,376,MetagrossMega Metagross,Steel,Psychic,700,80,145,150,105,110,110,3,False
418,380,LatiasMega Latias,Dragon,Psychic,700,80,100,120,140,150,110,3,True
420,381,LatiosMega Latios,Dragon,Psychic,700,80,130,100,160,120,110,3,True
426,384,RayquazaMega Rayquaza,Dragon,Flying,780,105,180,100,180,100,115,3,True
476,428,LopunnyMega Lopunny,Normal,Fighting,580,65,136,94,54,96,135,4,False
494,445,GarchompMega Garchomp,Dragon,Ground,700,108,170,115,120,95,92,4,False
498,448,LucarioMega Lucario,Fighting,Steel,625,70,145,88,140,70,112,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,594,90,132,105,132,105,30,4,False
527,475,GalladeMega Gallade,Psychic,Fighting,618,68,165,95,65,115,110,4,False
591,531,AudinoMega Audino,Normal,Fairy,545,103,60,126,80,126,50,5,False
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True

RegEx

In [78]:
import re
df.loc[df['Type 1'].str.contains('Fire|Grass',regex=True,flags=re.I)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,667,Litleo,Fire,Normal,369,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,507,86,68,72,109,66,106,6,False
740,672,Skiddo,Grass,NaN,350,66,65,48,62,57,52,6,False
741,673,Gogoat,Grass,NaN,531,123,100,62,97,81,68,6,False
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [80]:
df.loc[df['Name'].str.contains('^pi[a-z]*',flags=re.I,regex=True)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
20,16,Pidgey,Normal,Flying,251,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,349,63,60,55,50,50,71,1,False
22,18,Pidgeot,Normal,Flying,479,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False
30,25,Pikachu,Electric,NaN,320,35,55,40,50,50,90,1,False
136,127,Pinsir,Bug,NaN,500,65,125,100,55,70,85,1,False
137,127,PinsirMega Pinsir,Bug,Flying,600,65,155,120,65,90,105,1,False
186,172,Pichu,Electric,NaN,205,20,40,15,35,35,60,2,False
219,204,Pineco,Bug,NaN,290,50,65,90,35,35,15,2,False
239,221,Piloswine,Ice,Ground,450,100,100,80,60,60,50,2,False
438,393,Piplup,Water,NaN,314,53,51,53,61,56,40,4,False
558,499,Pignite,Fire,Fighting,418,90,93,55,70,55,55,5,False
578,519,Pidove,Normal,Flying,264,50,55,50,36,30,43,5,False

Conditional Changes

In [ ]:
# if type 1 is fire change it into flamer
df.loc[df['Type 1']=='Flamer','Type 1']='Fire'
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [83]:
df.loc[df['Type 1']=='Fire','Legendary']='True'
df

C:\Users\sirip\AppData\Local\Temp\ipykernel_12328\2340127624.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df.loc[df['Type 1']=='Fire','Legendary']='True'

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [84]:
df=pd.read_csv('modified_pokemon.csv')